# Generated by Django 4.2.2 on 2023-06-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactinformation_feedback_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
